#!/bin/sh

if pidof conky | grep [0-9] > /dev/null
then
	exec /usr/bin/killall conky
else
    /bin/bash ~/.conky/1_accuweather/1_accuweather -f2015 -h2015 -h_8h -h_no_forecast
	/usr/bin/conky -c ~/.conky/.conkyrc &
	/usr/bin/conky -c ~/.conky/.conkyrc_fs &
	/usr/bin/conky -c ~/.conky/1_accuweather/.conkyrc_1_hourly_2015 &
	/usr/bin/conky -c ~/.conky/1_accuweather/.conkyrc_1_images_2015 &
	exit 0
fi
