#!/bin/sh
# click to start, click to stop

if pidof conky | grep [0-9] > /dev/null
then
	exec killall conky
else
	###   sleep 1  # sleep not required for xfce or dropbox upto - 30 or more for others
	(sleep 1s &&  /usr/bin/conky -c ~/.conky/.conkyrc &) &
	(sleep 1s &&  /usr/bin/conky -c ~/.conky/.conkyrc_fs) &
	(sleep 10s && /usr/bin/conky -c ~/.conky/1_accuweather/.conkyrc_1b1) &
	(sleep 10s && /usr/bin/conky -c ~/.conky/1_accuweather/.conkyrc_1c) &
	exit 0
fi
